name: 'test.action'
author : dmvict <dm.vict.kr@gmail.com>
description: 'An action for testing purpose, no real usage expected.'
inputs:
  singleline:
    description: 'Multiline option'
  multiline:
    description: 'Multiline option'
  true_v:
    description: 'Multiline option'
outputs:
  string:
    description: 'Summary'
runs:
  using: 'node20'
  main: 'src/index.js'
