name: 'test.action'
author : dmvict <dm.vict.kr@gmail.com>
description: 'An action for testing purpose, no real usage expected.'
inputs:
  value:
    description: 'A test value'
    required: true
    default: 0
runs:
  using: 'node12'
  main: '../../src/index.js'
